export type CreateDriftSnapshotInput = {
    siteUrl?: string | null;
    windowType: string;
    tierAgreementRate: number;
    decisionAgreementRate: number;
    avgCompositeDivergence: number;
    sampleCount: number;
    avgIntentConverted?: number | null;
    avgIntentDismissed?: number | null;
    avgFrictionConverted?: number | null;
    avgFrictionDismissed?: number | null;
    avgClarityConverted?: number | null;
    avgClarityDismissed?: number | null;
    avgReceptivityConverted?: number | null;
    avgReceptivityDismissed?: number | null;
    avgValueConverted?: number | null;
    avgValueDismissed?: number | null;
    avgCompositeConverted?: number | null;
    avgCompositeDismissed?: number | null;
    conversionRate?: number | null;
    dismissalRate?: number | null;
};
export declare function createSnapshot(data: CreateDriftSnapshotInput): Promise<{
    id: string;
    siteUrl: string | null;
    createdAt: Date;
    windowType: string;
    tierAgreementRate: number;
    decisionAgreementRate: number;
    avgCompositeDivergence: number;
    sampleCount: number;
    avgIntentConverted: number | null;
    avgIntentDismissed: number | null;
    avgFrictionConverted: number | null;
    avgFrictionDismissed: number | null;
    avgClarityConverted: number | null;
    avgClarityDismissed: number | null;
    avgReceptivityConverted: number | null;
    avgReceptivityDismissed: number | null;
    avgValueConverted: number | null;
    avgValueDismissed: number | null;
    avgCompositeConverted: number | null;
    avgCompositeDismissed: number | null;
    conversionRate: number | null;
    dismissalRate: number | null;
}>;
export declare function listSnapshots(options?: {
    siteUrl?: string | null;
    windowType?: string;
    since?: Date;
    until?: Date;
    limit?: number;
    offset?: number;
}): Promise<{
    id: string;
    siteUrl: string | null;
    createdAt: Date;
    windowType: string;
    tierAgreementRate: number;
    decisionAgreementRate: number;
    avgCompositeDivergence: number;
    sampleCount: number;
    avgIntentConverted: number | null;
    avgIntentDismissed: number | null;
    avgFrictionConverted: number | null;
    avgFrictionDismissed: number | null;
    avgClarityConverted: number | null;
    avgClarityDismissed: number | null;
    avgReceptivityConverted: number | null;
    avgReceptivityDismissed: number | null;
    avgValueConverted: number | null;
    avgValueDismissed: number | null;
    avgCompositeConverted: number | null;
    avgCompositeDismissed: number | null;
    conversionRate: number | null;
    dismissalRate: number | null;
}[]>;
export declare function getLatestSnapshot(windowType: string, siteUrl?: string | null): Promise<{
    id: string;
    siteUrl: string | null;
    createdAt: Date;
    windowType: string;
    tierAgreementRate: number;
    decisionAgreementRate: number;
    avgCompositeDivergence: number;
    sampleCount: number;
    avgIntentConverted: number | null;
    avgIntentDismissed: number | null;
    avgFrictionConverted: number | null;
    avgFrictionDismissed: number | null;
    avgClarityConverted: number | null;
    avgClarityDismissed: number | null;
    avgReceptivityConverted: number | null;
    avgReceptivityDismissed: number | null;
    avgValueConverted: number | null;
    avgValueDismissed: number | null;
    avgCompositeConverted: number | null;
    avgCompositeDismissed: number | null;
    conversionRate: number | null;
    dismissalRate: number | null;
} | null>;
export declare function pruneOldSnapshots(olderThan: Date): Promise<import(".prisma/client").Prisma.BatchPayload>;
//# sourceMappingURL=drift-snapshot.repo.d.ts.map