export type CreateRolloutInput = {
    name: string;
    siteUrl?: string | null;
    changeType: string;
    newConfigId?: string;
    newEvalEngine?: string;
    configPayload?: string;
    stages: string;
    healthCriteria: string;
    experimentId?: string;
};
export declare function createRollout(data: CreateRolloutInput): Promise<{
    status: string;
    name: string;
    id: string;
    siteUrl: string | null;
    startedAt: Date | null;
    createdAt: Date;
    updatedAt: Date;
    completedAt: Date | null;
    experimentId: string | null;
    changeType: string;
    newConfigId: string | null;
    newEvalEngine: string | null;
    configPayload: string | null;
    stages: string;
    currentStage: number;
    healthCriteria: string;
    rolledBackAt: Date | null;
    rollbackReason: string | null;
    lastHealthCheck: Date | null;
    lastHealthStatus: string | null;
}>;
export declare function getRollout(id: string): Promise<({
    experiment: {
        status: string;
        name: string;
        id: string;
        siteUrl: string | null;
        startedAt: Date | null;
        endedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        description: string | null;
        trafficPercent: number;
        variants: string;
        primaryMetric: string;
        minSampleSize: number;
    } | null;
} & {
    status: string;
    name: string;
    id: string;
    siteUrl: string | null;
    startedAt: Date | null;
    createdAt: Date;
    updatedAt: Date;
    completedAt: Date | null;
    experimentId: string | null;
    changeType: string;
    newConfigId: string | null;
    newEvalEngine: string | null;
    configPayload: string | null;
    stages: string;
    currentStage: number;
    healthCriteria: string;
    rolledBackAt: Date | null;
    rollbackReason: string | null;
    lastHealthCheck: Date | null;
    lastHealthStatus: string | null;
}) | null>;
export declare function updateRollout(id: string, data: Partial<{
    status: string;
    currentStage: number;
    startedAt: Date;
    completedAt: Date;
    rolledBackAt: Date;
    rollbackReason: string;
    lastHealthCheck: Date;
    lastHealthStatus: string;
    experimentId: string;
}>): Promise<{
    status: string;
    name: string;
    id: string;
    siteUrl: string | null;
    startedAt: Date | null;
    createdAt: Date;
    updatedAt: Date;
    completedAt: Date | null;
    experimentId: string | null;
    changeType: string;
    newConfigId: string | null;
    newEvalEngine: string | null;
    configPayload: string | null;
    stages: string;
    currentStage: number;
    healthCriteria: string;
    rolledBackAt: Date | null;
    rollbackReason: string | null;
    lastHealthCheck: Date | null;
    lastHealthStatus: string | null;
}>;
export declare function advanceStage(id: string): Promise<{
    status: string;
    name: string;
    id: string;
    siteUrl: string | null;
    startedAt: Date | null;
    createdAt: Date;
    updatedAt: Date;
    completedAt: Date | null;
    experimentId: string | null;
    changeType: string;
    newConfigId: string | null;
    newEvalEngine: string | null;
    configPayload: string | null;
    stages: string;
    currentStage: number;
    healthCriteria: string;
    rolledBackAt: Date | null;
    rollbackReason: string | null;
    lastHealthCheck: Date | null;
    lastHealthStatus: string | null;
}>;
export declare function completeRollout(id: string): Promise<{
    status: string;
    name: string;
    id: string;
    siteUrl: string | null;
    startedAt: Date | null;
    createdAt: Date;
    updatedAt: Date;
    completedAt: Date | null;
    experimentId: string | null;
    changeType: string;
    newConfigId: string | null;
    newEvalEngine: string | null;
    configPayload: string | null;
    stages: string;
    currentStage: number;
    healthCriteria: string;
    rolledBackAt: Date | null;
    rollbackReason: string | null;
    lastHealthCheck: Date | null;
    lastHealthStatus: string | null;
}>;
export declare function rollback(id: string, reason: string): Promise<{
    status: string;
    name: string;
    id: string;
    siteUrl: string | null;
    startedAt: Date | null;
    createdAt: Date;
    updatedAt: Date;
    completedAt: Date | null;
    experimentId: string | null;
    changeType: string;
    newConfigId: string | null;
    newEvalEngine: string | null;
    configPayload: string | null;
    stages: string;
    currentStage: number;
    healthCriteria: string;
    rolledBackAt: Date | null;
    rollbackReason: string | null;
    lastHealthCheck: Date | null;
    lastHealthStatus: string | null;
}>;
export declare function getActiveRollout(siteUrl?: string | null): Promise<({
    experiment: {
        status: string;
        name: string;
        id: string;
        siteUrl: string | null;
        startedAt: Date | null;
        endedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        description: string | null;
        trafficPercent: number;
        variants: string;
        primaryMetric: string;
        minSampleSize: number;
    } | null;
} & {
    status: string;
    name: string;
    id: string;
    siteUrl: string | null;
    startedAt: Date | null;
    createdAt: Date;
    updatedAt: Date;
    completedAt: Date | null;
    experimentId: string | null;
    changeType: string;
    newConfigId: string | null;
    newEvalEngine: string | null;
    configPayload: string | null;
    stages: string;
    currentStage: number;
    healthCriteria: string;
    rolledBackAt: Date | null;
    rollbackReason: string | null;
    lastHealthCheck: Date | null;
    lastHealthStatus: string | null;
}) | null>;
export declare function listRollouts(options?: {
    status?: string;
    siteUrl?: string | null;
    limit?: number;
    offset?: number;
}): Promise<({
    experiment: {
        status: string;
        name: string;
        id: string;
        siteUrl: string | null;
        startedAt: Date | null;
        endedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        description: string | null;
        trafficPercent: number;
        variants: string;
        primaryMetric: string;
        minSampleSize: number;
    } | null;
} & {
    status: string;
    name: string;
    id: string;
    siteUrl: string | null;
    startedAt: Date | null;
    createdAt: Date;
    updatedAt: Date;
    completedAt: Date | null;
    experimentId: string | null;
    changeType: string;
    newConfigId: string | null;
    newEvalEngine: string | null;
    configPayload: string | null;
    stages: string;
    currentStage: number;
    healthCriteria: string;
    rolledBackAt: Date | null;
    rollbackReason: string | null;
    lastHealthCheck: Date | null;
    lastHealthStatus: string | null;
})[]>;
//# sourceMappingURL=rollout.repo.d.ts.map