export type CreateScoringConfigInput = {
    name: string;
    siteUrl?: string;
    isActive?: boolean;
    weightIntent?: number;
    weightFriction?: number;
    weightClarity?: number;
    weightReceptivity?: number;
    weightValue?: number;
    thresholdMonitor?: number;
    thresholdPassive?: number;
    thresholdNudge?: number;
    thresholdActive?: number;
    minSessionAgeSec?: number;
    maxActivePerSession?: number;
    maxNudgePerSession?: number;
    maxNonPassivePerSession?: number;
    cooldownAfterActiveSec?: number;
    cooldownAfterNudgeSec?: number;
    cooldownAfterDismissSec?: number;
    dismissalsToSuppress?: number;
};
export type UpdateScoringConfigInput = Partial<CreateScoringConfigInput>;
export declare function createScoringConfig(data: CreateScoringConfigInput): Promise<{
    name: string;
    id: string;
    siteUrl: string | null;
    isActive: boolean;
    weightIntent: number;
    weightFriction: number;
    weightClarity: number;
    weightReceptivity: number;
    weightValue: number;
    thresholdMonitor: number;
    thresholdPassive: number;
    thresholdNudge: number;
    thresholdActive: number;
    minSessionAgeSec: number;
    maxActivePerSession: number;
    maxNudgePerSession: number;
    maxNonPassivePerSession: number;
    cooldownAfterActiveSec: number;
    cooldownAfterNudgeSec: number;
    cooldownAfterDismissSec: number;
    dismissalsToSuppress: number;
    createdAt: Date;
    updatedAt: Date;
}>;
export declare function getScoringConfig(id: string): Promise<{
    name: string;
    id: string;
    siteUrl: string | null;
    isActive: boolean;
    weightIntent: number;
    weightFriction: number;
    weightClarity: number;
    weightReceptivity: number;
    weightValue: number;
    thresholdMonitor: number;
    thresholdPassive: number;
    thresholdNudge: number;
    thresholdActive: number;
    minSessionAgeSec: number;
    maxActivePerSession: number;
    maxNudgePerSession: number;
    maxNonPassivePerSession: number;
    cooldownAfterActiveSec: number;
    cooldownAfterNudgeSec: number;
    cooldownAfterDismissSec: number;
    dismissalsToSuppress: number;
    createdAt: Date;
    updatedAt: Date;
} | null>;
export declare function updateScoringConfig(id: string, data: UpdateScoringConfigInput): Promise<{
    name: string;
    id: string;
    siteUrl: string | null;
    isActive: boolean;
    weightIntent: number;
    weightFriction: number;
    weightClarity: number;
    weightReceptivity: number;
    weightValue: number;
    thresholdMonitor: number;
    thresholdPassive: number;
    thresholdNudge: number;
    thresholdActive: number;
    minSessionAgeSec: number;
    maxActivePerSession: number;
    maxNudgePerSession: number;
    maxNonPassivePerSession: number;
    cooldownAfterActiveSec: number;
    cooldownAfterNudgeSec: number;
    cooldownAfterDismissSec: number;
    dismissalsToSuppress: number;
    createdAt: Date;
    updatedAt: Date;
}>;
export declare function deleteScoringConfig(id: string): Promise<{
    name: string;
    id: string;
    siteUrl: string | null;
    isActive: boolean;
    weightIntent: number;
    weightFriction: number;
    weightClarity: number;
    weightReceptivity: number;
    weightValue: number;
    thresholdMonitor: number;
    thresholdPassive: number;
    thresholdNudge: number;
    thresholdActive: number;
    minSessionAgeSec: number;
    maxActivePerSession: number;
    maxNudgePerSession: number;
    maxNonPassivePerSession: number;
    cooldownAfterActiveSec: number;
    cooldownAfterNudgeSec: number;
    cooldownAfterDismissSec: number;
    dismissalsToSuppress: number;
    createdAt: Date;
    updatedAt: Date;
}>;
/**
 * Get the active scoring config for a given site URL.
 * Falls back to global default (siteUrl == null) if no site-specific config.
 */
export declare function getActiveConfig(siteUrl?: string): Promise<{
    name: string;
    id: string;
    siteUrl: string | null;
    isActive: boolean;
    weightIntent: number;
    weightFriction: number;
    weightClarity: number;
    weightReceptivity: number;
    weightValue: number;
    thresholdMonitor: number;
    thresholdPassive: number;
    thresholdNudge: number;
    thresholdActive: number;
    minSessionAgeSec: number;
    maxActivePerSession: number;
    maxNudgePerSession: number;
    maxNonPassivePerSession: number;
    cooldownAfterActiveSec: number;
    cooldownAfterNudgeSec: number;
    cooldownAfterDismissSec: number;
    dismissalsToSuppress: number;
    createdAt: Date;
    updatedAt: Date;
} | null>;
/**
 * Set a config as active, deactivating any other active config for the same scope.
 */
export declare function activateConfig(id: string): Promise<{
    name: string;
    id: string;
    siteUrl: string | null;
    isActive: boolean;
    weightIntent: number;
    weightFriction: number;
    weightClarity: number;
    weightReceptivity: number;
    weightValue: number;
    thresholdMonitor: number;
    thresholdPassive: number;
    thresholdNudge: number;
    thresholdActive: number;
    minSessionAgeSec: number;
    maxActivePerSession: number;
    maxNudgePerSession: number;
    maxNonPassivePerSession: number;
    cooldownAfterActiveSec: number;
    cooldownAfterNudgeSec: number;
    cooldownAfterDismissSec: number;
    dismissalsToSuppress: number;
    createdAt: Date;
    updatedAt: Date;
}>;
export declare function listScoringConfigs(): Promise<{
    name: string;
    id: string;
    siteUrl: string | null;
    isActive: boolean;
    weightIntent: number;
    weightFriction: number;
    weightClarity: number;
    weightReceptivity: number;
    weightValue: number;
    thresholdMonitor: number;
    thresholdPassive: number;
    thresholdNudge: number;
    thresholdActive: number;
    minSessionAgeSec: number;
    maxActivePerSession: number;
    maxNudgePerSession: number;
    maxNonPassivePerSession: number;
    cooldownAfterActiveSec: number;
    cooldownAfterNudgeSec: number;
    cooldownAfterDismissSec: number;
    dismissalsToSuppress: number;
    createdAt: Date;
    updatedAt: Date;
}[]>;
export declare function listScoringConfigsBySite(siteUrl: string): Promise<{
    name: string;
    id: string;
    siteUrl: string | null;
    isActive: boolean;
    weightIntent: number;
    weightFriction: number;
    weightClarity: number;
    weightReceptivity: number;
    weightValue: number;
    thresholdMonitor: number;
    thresholdPassive: number;
    thresholdNudge: number;
    thresholdActive: number;
    minSessionAgeSec: number;
    maxActivePerSession: number;
    maxNudgePerSession: number;
    maxNonPassivePerSession: number;
    cooldownAfterActiveSec: number;
    cooldownAfterNudgeSec: number;
    cooldownAfterDismissSec: number;
    dismissalsToSuppress: number;
    createdAt: Date;
    updatedAt: Date;
}[]>;
//# sourceMappingURL=scoring-config.repo.d.ts.map