export type CreateSessionInput = {
    visitorId?: string;
    siteUrl: string;
    deviceType: string;
    referrerType: string;
    isLoggedIn?: boolean;
    isRepeatVisitor?: boolean;
};
export type UpdateSessionInput = Partial<{
    lastActivityAt: Date;
    cartValue: number;
    cartItemCount: number;
    status: string;
    isLoggedIn: boolean;
    totalInterventionsFired: number;
    totalDismissals: number;
    totalConversions: number;
    suppressNonPassive: boolean;
    totalVoiceInterventionsFired: number;
    voiceMuted: boolean;
}>;
export declare function createSession(data: CreateSessionInput): Promise<{
    status: string;
    id: string;
    visitorId: string | null;
    siteUrl: string;
    startedAt: Date;
    lastActivityAt: Date;
    deviceType: string;
    referrerType: string;
    isLoggedIn: boolean;
    isRepeatVisitor: boolean;
    cartValue: number;
    cartItemCount: number;
    totalInterventionsFired: number;
    totalDismissals: number;
    totalConversions: number;
    suppressNonPassive: boolean;
    totalVoiceInterventionsFired: number;
    voiceMuted: boolean;
    attributedRevenue: number;
    isControlSession: boolean;
    endedAt: Date | null;
    totalPageViews: number;
    totalTimeOnSiteMs: number | null;
    entryPage: string | null;
    exitPage: string | null;
    landingReferrer: string | null;
    utmSource: string | null;
    utmMedium: string | null;
    utmCampaign: string | null;
    utmContent: string | null;
    utmTerm: string | null;
}>;
export declare function getSession(id: string): Promise<({} & {
    status: string;
    id: string;
    visitorId: string | null;
    siteUrl: string;
    startedAt: Date;
    lastActivityAt: Date;
    deviceType: string;
    referrerType: string;
    isLoggedIn: boolean;
    isRepeatVisitor: boolean;
    cartValue: number;
    cartItemCount: number;
    totalInterventionsFired: number;
    totalDismissals: number;
    totalConversions: number;
    suppressNonPassive: boolean;
    totalVoiceInterventionsFired: number;
    voiceMuted: boolean;
    attributedRevenue: number;
    isControlSession: boolean;
    endedAt: Date | null;
    totalPageViews: number;
    totalTimeOnSiteMs: number | null;
    entryPage: string | null;
    exitPage: string | null;
    landingReferrer: string | null;
    utmSource: string | null;
    utmMedium: string | null;
    utmCampaign: string | null;
    utmContent: string | null;
    utmTerm: string | null;
}) | null>;
export declare function getSessionFull(id: string): Promise<({
    events: {
        id: string;
        siteUrl: string | null;
        sessionId: string;
        timestamp: Date;
        category: string;
        eventType: string;
        frictionId: string | null;
        pageType: string;
        pageUrl: string;
        rawSignals: string;
        metadata: string | null;
        previousPageUrl: string | null;
        timeOnPageMs: number | null;
        scrollDepthPct: number | null;
        sessionSequenceNumber: number | null;
    }[];
    evaluations: {
        id: string;
        sessionId: string;
        timestamp: Date;
        eventBatchIds: string;
        narrative: string;
        frictionsFound: string;
        intentScore: number;
        frictionScore: number;
        clarityScore: number;
        receptivityScore: number;
        valueScore: number;
        engine: string;
        compositeScore: number;
        weightsUsed: string;
        tier: string;
        decision: string;
        gateOverride: string | null;
        interventionType: string | null;
        reasoning: string;
        detectedBehaviors: string | null;
        abandonmentScore: number | null;
    }[];
    interventions: {
        status: string;
        id: string;
        sessionId: string;
        timestamp: Date;
        frictionId: string;
        evaluationId: string;
        type: string;
        actionCode: string;
        payload: string;
        deliveredAt: Date | null;
        dismissedAt: Date | null;
        convertedAt: Date | null;
        ignoredAt: Date | null;
        conversionAction: string | null;
        mswimScoreAtFire: number;
        tierAtFire: string;
        cartValueAtFire: number | null;
        cartValueAtConversion: number | null;
    }[];
} & {
    status: string;
    id: string;
    visitorId: string | null;
    siteUrl: string;
    startedAt: Date;
    lastActivityAt: Date;
    deviceType: string;
    referrerType: string;
    isLoggedIn: boolean;
    isRepeatVisitor: boolean;
    cartValue: number;
    cartItemCount: number;
    totalInterventionsFired: number;
    totalDismissals: number;
    totalConversions: number;
    suppressNonPassive: boolean;
    totalVoiceInterventionsFired: number;
    voiceMuted: boolean;
    attributedRevenue: number;
    isControlSession: boolean;
    endedAt: Date | null;
    totalPageViews: number;
    totalTimeOnSiteMs: number | null;
    entryPage: string | null;
    exitPage: string | null;
    landingReferrer: string | null;
    utmSource: string | null;
    utmMedium: string | null;
    utmCampaign: string | null;
    utmContent: string | null;
    utmTerm: string | null;
}) | null>;
export declare function updateSession(id: string, data: UpdateSessionInput): Promise<{
    status: string;
    id: string;
    visitorId: string | null;
    siteUrl: string;
    startedAt: Date;
    lastActivityAt: Date;
    deviceType: string;
    referrerType: string;
    isLoggedIn: boolean;
    isRepeatVisitor: boolean;
    cartValue: number;
    cartItemCount: number;
    totalInterventionsFired: number;
    totalDismissals: number;
    totalConversions: number;
    suppressNonPassive: boolean;
    totalVoiceInterventionsFired: number;
    voiceMuted: boolean;
    attributedRevenue: number;
    isControlSession: boolean;
    endedAt: Date | null;
    totalPageViews: number;
    totalTimeOnSiteMs: number | null;
    entryPage: string | null;
    exitPage: string | null;
    landingReferrer: string | null;
    utmSource: string | null;
    utmMedium: string | null;
    utmCampaign: string | null;
    utmContent: string | null;
    utmTerm: string | null;
}>;
export declare function touchSession(id: string): Promise<{
    status: string;
    id: string;
    visitorId: string | null;
    siteUrl: string;
    startedAt: Date;
    lastActivityAt: Date;
    deviceType: string;
    referrerType: string;
    isLoggedIn: boolean;
    isRepeatVisitor: boolean;
    cartValue: number;
    cartItemCount: number;
    totalInterventionsFired: number;
    totalDismissals: number;
    totalConversions: number;
    suppressNonPassive: boolean;
    totalVoiceInterventionsFired: number;
    voiceMuted: boolean;
    attributedRevenue: number;
    isControlSession: boolean;
    endedAt: Date | null;
    totalPageViews: number;
    totalTimeOnSiteMs: number | null;
    entryPage: string | null;
    exitPage: string | null;
    landingReferrer: string | null;
    utmSource: string | null;
    utmMedium: string | null;
    utmCampaign: string | null;
    utmContent: string | null;
    utmTerm: string | null;
}>;
export declare function endSession(id: string): Promise<{
    status: string;
    id: string;
    visitorId: string | null;
    siteUrl: string;
    startedAt: Date;
    lastActivityAt: Date;
    deviceType: string;
    referrerType: string;
    isLoggedIn: boolean;
    isRepeatVisitor: boolean;
    cartValue: number;
    cartItemCount: number;
    totalInterventionsFired: number;
    totalDismissals: number;
    totalConversions: number;
    suppressNonPassive: boolean;
    totalVoiceInterventionsFired: number;
    voiceMuted: boolean;
    attributedRevenue: number;
    isControlSession: boolean;
    endedAt: Date | null;
    totalPageViews: number;
    totalTimeOnSiteMs: number | null;
    entryPage: string | null;
    exitPage: string | null;
    landingReferrer: string | null;
    utmSource: string | null;
    utmMedium: string | null;
    utmCampaign: string | null;
    utmContent: string | null;
    utmTerm: string | null;
}>;
export declare function incrementInterventionsFired(id: string): Promise<{
    status: string;
    id: string;
    visitorId: string | null;
    siteUrl: string;
    startedAt: Date;
    lastActivityAt: Date;
    deviceType: string;
    referrerType: string;
    isLoggedIn: boolean;
    isRepeatVisitor: boolean;
    cartValue: number;
    cartItemCount: number;
    totalInterventionsFired: number;
    totalDismissals: number;
    totalConversions: number;
    suppressNonPassive: boolean;
    totalVoiceInterventionsFired: number;
    voiceMuted: boolean;
    attributedRevenue: number;
    isControlSession: boolean;
    endedAt: Date | null;
    totalPageViews: number;
    totalTimeOnSiteMs: number | null;
    entryPage: string | null;
    exitPage: string | null;
    landingReferrer: string | null;
    utmSource: string | null;
    utmMedium: string | null;
    utmCampaign: string | null;
    utmContent: string | null;
    utmTerm: string | null;
}>;
export declare function incrementDismissals(id: string): Promise<{
    status: string;
    id: string;
    visitorId: string | null;
    siteUrl: string;
    startedAt: Date;
    lastActivityAt: Date;
    deviceType: string;
    referrerType: string;
    isLoggedIn: boolean;
    isRepeatVisitor: boolean;
    cartValue: number;
    cartItemCount: number;
    totalInterventionsFired: number;
    totalDismissals: number;
    totalConversions: number;
    suppressNonPassive: boolean;
    totalVoiceInterventionsFired: number;
    voiceMuted: boolean;
    attributedRevenue: number;
    isControlSession: boolean;
    endedAt: Date | null;
    totalPageViews: number;
    totalTimeOnSiteMs: number | null;
    entryPage: string | null;
    exitPage: string | null;
    landingReferrer: string | null;
    utmSource: string | null;
    utmMedium: string | null;
    utmCampaign: string | null;
    utmContent: string | null;
    utmTerm: string | null;
}>;
export declare function incrementConversions(id: string): Promise<{
    status: string;
    id: string;
    visitorId: string | null;
    siteUrl: string;
    startedAt: Date;
    lastActivityAt: Date;
    deviceType: string;
    referrerType: string;
    isLoggedIn: boolean;
    isRepeatVisitor: boolean;
    cartValue: number;
    cartItemCount: number;
    totalInterventionsFired: number;
    totalDismissals: number;
    totalConversions: number;
    suppressNonPassive: boolean;
    totalVoiceInterventionsFired: number;
    voiceMuted: boolean;
    attributedRevenue: number;
    isControlSession: boolean;
    endedAt: Date | null;
    totalPageViews: number;
    totalTimeOnSiteMs: number | null;
    entryPage: string | null;
    exitPage: string | null;
    landingReferrer: string | null;
    utmSource: string | null;
    utmMedium: string | null;
    utmCampaign: string | null;
    utmContent: string | null;
    utmTerm: string | null;
}>;
/**
 * Add cart lift to Session.attributedRevenue.
 * Called when an intervention converts — adds the delta (cartNow - cartAtFire).
 */
export declare function addAttributedRevenue(id: string, lift: number): Promise<{
    status: string;
    id: string;
    visitorId: string | null;
    siteUrl: string;
    startedAt: Date;
    lastActivityAt: Date;
    deviceType: string;
    referrerType: string;
    isLoggedIn: boolean;
    isRepeatVisitor: boolean;
    cartValue: number;
    cartItemCount: number;
    totalInterventionsFired: number;
    totalDismissals: number;
    totalConversions: number;
    suppressNonPassive: boolean;
    totalVoiceInterventionsFired: number;
    voiceMuted: boolean;
    attributedRevenue: number;
    isControlSession: boolean;
    endedAt: Date | null;
    totalPageViews: number;
    totalTimeOnSiteMs: number | null;
    entryPage: string | null;
    exitPage: string | null;
    landingReferrer: string | null;
    utmSource: string | null;
    utmMedium: string | null;
    utmCampaign: string | null;
    utmContent: string | null;
    utmTerm: string | null;
} | undefined>;
/**
 * Mark session as part of the 5% control group (no interventions fired).
 */
export declare function markControlSession(id: string): Promise<{
    status: string;
    id: string;
    visitorId: string | null;
    siteUrl: string;
    startedAt: Date;
    lastActivityAt: Date;
    deviceType: string;
    referrerType: string;
    isLoggedIn: boolean;
    isRepeatVisitor: boolean;
    cartValue: number;
    cartItemCount: number;
    totalInterventionsFired: number;
    totalDismissals: number;
    totalConversions: number;
    suppressNonPassive: boolean;
    totalVoiceInterventionsFired: number;
    voiceMuted: boolean;
    attributedRevenue: number;
    isControlSession: boolean;
    endedAt: Date | null;
    totalPageViews: number;
    totalTimeOnSiteMs: number | null;
    entryPage: string | null;
    exitPage: string | null;
    landingReferrer: string | null;
    utmSource: string | null;
    utmMedium: string | null;
    utmCampaign: string | null;
    utmContent: string | null;
    utmTerm: string | null;
}>;
export declare function setSuppressNonPassive(id: string, suppress: boolean): Promise<{
    status: string;
    id: string;
    visitorId: string | null;
    siteUrl: string;
    startedAt: Date;
    lastActivityAt: Date;
    deviceType: string;
    referrerType: string;
    isLoggedIn: boolean;
    isRepeatVisitor: boolean;
    cartValue: number;
    cartItemCount: number;
    totalInterventionsFired: number;
    totalDismissals: number;
    totalConversions: number;
    suppressNonPassive: boolean;
    totalVoiceInterventionsFired: number;
    voiceMuted: boolean;
    attributedRevenue: number;
    isControlSession: boolean;
    endedAt: Date | null;
    totalPageViews: number;
    totalTimeOnSiteMs: number | null;
    entryPage: string | null;
    exitPage: string | null;
    landingReferrer: string | null;
    utmSource: string | null;
    utmMedium: string | null;
    utmCampaign: string | null;
    utmContent: string | null;
    utmTerm: string | null;
}>;
export declare function incrementVoiceInterventionsFired(id: string): Promise<{
    status: string;
    id: string;
    visitorId: string | null;
    siteUrl: string;
    startedAt: Date;
    lastActivityAt: Date;
    deviceType: string;
    referrerType: string;
    isLoggedIn: boolean;
    isRepeatVisitor: boolean;
    cartValue: number;
    cartItemCount: number;
    totalInterventionsFired: number;
    totalDismissals: number;
    totalConversions: number;
    suppressNonPassive: boolean;
    totalVoiceInterventionsFired: number;
    voiceMuted: boolean;
    attributedRevenue: number;
    isControlSession: boolean;
    endedAt: Date | null;
    totalPageViews: number;
    totalTimeOnSiteMs: number | null;
    entryPage: string | null;
    exitPage: string | null;
    landingReferrer: string | null;
    utmSource: string | null;
    utmMedium: string | null;
    utmCampaign: string | null;
    utmContent: string | null;
    utmTerm: string | null;
}>;
export declare function setVoiceMuted(id: string): Promise<{
    status: string;
    id: string;
    visitorId: string | null;
    siteUrl: string;
    startedAt: Date;
    lastActivityAt: Date;
    deviceType: string;
    referrerType: string;
    isLoggedIn: boolean;
    isRepeatVisitor: boolean;
    cartValue: number;
    cartItemCount: number;
    totalInterventionsFired: number;
    totalDismissals: number;
    totalConversions: number;
    suppressNonPassive: boolean;
    totalVoiceInterventionsFired: number;
    voiceMuted: boolean;
    attributedRevenue: number;
    isControlSession: boolean;
    endedAt: Date | null;
    totalPageViews: number;
    totalTimeOnSiteMs: number | null;
    entryPage: string | null;
    exitPage: string | null;
    landingReferrer: string | null;
    utmSource: string | null;
    utmMedium: string | null;
    utmCampaign: string | null;
    utmContent: string | null;
    utmTerm: string | null;
}>;
export declare function listActiveSessions(siteUrl?: string): Promise<{
    status: string;
    id: string;
    visitorId: string | null;
    siteUrl: string;
    startedAt: Date;
    lastActivityAt: Date;
    deviceType: string;
    referrerType: string;
    isLoggedIn: boolean;
    isRepeatVisitor: boolean;
    cartValue: number;
    cartItemCount: number;
    totalInterventionsFired: number;
    totalDismissals: number;
    totalConversions: number;
    suppressNonPassive: boolean;
    totalVoiceInterventionsFired: number;
    voiceMuted: boolean;
    attributedRevenue: number;
    isControlSession: boolean;
    endedAt: Date | null;
    totalPageViews: number;
    totalTimeOnSiteMs: number | null;
    entryPage: string | null;
    exitPage: string | null;
    landingReferrer: string | null;
    utmSource: string | null;
    utmMedium: string | null;
    utmCampaign: string | null;
    utmContent: string | null;
    utmTerm: string | null;
}[]>;
export declare function getRecentSessions(limit?: number): Promise<{
    status: string;
    id: string;
    visitorId: string | null;
    siteUrl: string;
    startedAt: Date;
    lastActivityAt: Date;
    deviceType: string;
    referrerType: string;
    isLoggedIn: boolean;
    isRepeatVisitor: boolean;
    cartValue: number;
    cartItemCount: number;
    totalInterventionsFired: number;
    totalDismissals: number;
    totalConversions: number;
    suppressNonPassive: boolean;
    totalVoiceInterventionsFired: number;
    voiceMuted: boolean;
    attributedRevenue: number;
    isControlSession: boolean;
    endedAt: Date | null;
    totalPageViews: number;
    totalTimeOnSiteMs: number | null;
    entryPage: string | null;
    exitPage: string | null;
    landingReferrer: string | null;
    utmSource: string | null;
    utmMedium: string | null;
    utmCampaign: string | null;
    utmContent: string | null;
    utmTerm: string | null;
}[]>;
export declare function incrementPageViews(id: string): Promise<{
    status: string;
    id: string;
    visitorId: string | null;
    siteUrl: string;
    startedAt: Date;
    lastActivityAt: Date;
    deviceType: string;
    referrerType: string;
    isLoggedIn: boolean;
    isRepeatVisitor: boolean;
    cartValue: number;
    cartItemCount: number;
    totalInterventionsFired: number;
    totalDismissals: number;
    totalConversions: number;
    suppressNonPassive: boolean;
    totalVoiceInterventionsFired: number;
    voiceMuted: boolean;
    attributedRevenue: number;
    isControlSession: boolean;
    endedAt: Date | null;
    totalPageViews: number;
    totalTimeOnSiteMs: number | null;
    entryPage: string | null;
    exitPage: string | null;
    landingReferrer: string | null;
    utmSource: string | null;
    utmMedium: string | null;
    utmCampaign: string | null;
    utmContent: string | null;
    utmTerm: string | null;
}>;
export declare function setEntryPage(id: string, url: string, opts?: {
    landingReferrer?: string;
    utmSource?: string;
    utmMedium?: string;
    utmCampaign?: string;
    utmContent?: string;
    utmTerm?: string;
}): Promise<{
    status: string;
    id: string;
    visitorId: string | null;
    siteUrl: string;
    startedAt: Date;
    lastActivityAt: Date;
    deviceType: string;
    referrerType: string;
    isLoggedIn: boolean;
    isRepeatVisitor: boolean;
    cartValue: number;
    cartItemCount: number;
    totalInterventionsFired: number;
    totalDismissals: number;
    totalConversions: number;
    suppressNonPassive: boolean;
    totalVoiceInterventionsFired: number;
    voiceMuted: boolean;
    attributedRevenue: number;
    isControlSession: boolean;
    endedAt: Date | null;
    totalPageViews: number;
    totalTimeOnSiteMs: number | null;
    entryPage: string | null;
    exitPage: string | null;
    landingReferrer: string | null;
    utmSource: string | null;
    utmMedium: string | null;
    utmCampaign: string | null;
    utmContent: string | null;
    utmTerm: string | null;
}>;
export declare function setExitPage(id: string, url: string): Promise<{
    status: string;
    id: string;
    visitorId: string | null;
    siteUrl: string;
    startedAt: Date;
    lastActivityAt: Date;
    deviceType: string;
    referrerType: string;
    isLoggedIn: boolean;
    isRepeatVisitor: boolean;
    cartValue: number;
    cartItemCount: number;
    totalInterventionsFired: number;
    totalDismissals: number;
    totalConversions: number;
    suppressNonPassive: boolean;
    totalVoiceInterventionsFired: number;
    voiceMuted: boolean;
    attributedRevenue: number;
    isControlSession: boolean;
    endedAt: Date | null;
    totalPageViews: number;
    totalTimeOnSiteMs: number | null;
    entryPage: string | null;
    exitPage: string | null;
    landingReferrer: string | null;
    utmSource: string | null;
    utmMedium: string | null;
    utmCampaign: string | null;
    utmContent: string | null;
    utmTerm: string | null;
}>;
export declare function accumulateTimeOnSite(id: string, ms: number): Promise<{
    status: string;
    id: string;
    visitorId: string | null;
    siteUrl: string;
    startedAt: Date;
    lastActivityAt: Date;
    deviceType: string;
    referrerType: string;
    isLoggedIn: boolean;
    isRepeatVisitor: boolean;
    cartValue: number;
    cartItemCount: number;
    totalInterventionsFired: number;
    totalDismissals: number;
    totalConversions: number;
    suppressNonPassive: boolean;
    totalVoiceInterventionsFired: number;
    voiceMuted: boolean;
    attributedRevenue: number;
    isControlSession: boolean;
    endedAt: Date | null;
    totalPageViews: number;
    totalTimeOnSiteMs: number | null;
    entryPage: string | null;
    exitPage: string | null;
    landingReferrer: string | null;
    utmSource: string | null;
    utmMedium: string | null;
    utmCampaign: string | null;
    utmContent: string | null;
    utmTerm: string | null;
}>;
/** Bounce rate: sessions with exactly 1 page view divided by total sessions */
export declare function getBounceRate(siteUrl: string, since?: Date): Promise<{
    total: number;
    bounced: number;
    bounceRate: number;
}>;
/** Traffic source breakdown: group by referrerType with conversion stats */
export declare function getTrafficSourceBreakdown(siteUrl: string, since?: Date): Promise<{
    referrerType: string;
    sessions: number;
    conversions: number;
    conversionRate: number;
}[]>;
/** Device type breakdown with conversion stats */
export declare function getDeviceBreakdown(siteUrl: string, since?: Date): Promise<{
    deviceType: string;
    sessions: number;
    conversions: number;
    conversionRate: number;
}[]>;
/** Daily session volume over a time range */
export declare function getSessionVolumeByDay(siteUrl: string, since?: Date, until?: Date): Promise<{
    date: string;
    count: number;
}[]>;
/** Weekly retention cohort: new vs returning visitors by ISO week */
export declare function getRetentionCohort(siteUrl: string, since?: Date, until?: Date): Promise<{
    total: number;
    new: number;
    returning: number;
    week: string;
}[]>;
/** Avg session duration using lastActivityAt - startedAt as proxy */
export declare function getAvgSessionDuration(siteUrl: string, since?: Date): Promise<number>;
/** Avg page views per session */
export declare function getAvgPageViews(siteUrl: string, since?: Date): Promise<number>;
//# sourceMappingURL=session.repo.d.ts.map