export type CreateShadowComparisonInput = {
    sessionId: string;
    evaluationId: string;
    prodIntentScore: number;
    prodFrictionScore: number;
    prodClarityScore: number;
    prodReceptivityScore: number;
    prodValueScore: number;
    prodCompositeScore: number;
    prodTier: string;
    prodDecision: string;
    prodGateOverride?: string;
    shadowIntentScore: number;
    shadowFrictionScore: number;
    shadowClarityScore: number;
    shadowReceptivityScore: number;
    shadowValueScore: number;
    shadowCompositeScore: number;
    shadowTier: string;
    shadowDecision: string;
    shadowGateOverride?: string;
    compositeDivergence: number;
    tierMatch: boolean;
    decisionMatch: boolean;
    gateOverrideMatch: boolean;
    pageType: string;
    eventCount: number;
    cartValue: number;
    syntheticHints: string;
};
export declare function createComparison(data: CreateShadowComparisonInput): Promise<{
    id: string;
    cartValue: number;
    sessionId: string;
    pageType: string;
    evaluationId: string;
    createdAt: Date;
    prodIntentScore: number;
    prodFrictionScore: number;
    prodClarityScore: number;
    prodReceptivityScore: number;
    prodValueScore: number;
    prodCompositeScore: number;
    prodTier: string;
    prodDecision: string;
    prodGateOverride: string | null;
    shadowIntentScore: number;
    shadowFrictionScore: number;
    shadowClarityScore: number;
    shadowReceptivityScore: number;
    shadowValueScore: number;
    shadowCompositeScore: number;
    shadowTier: string;
    shadowDecision: string;
    shadowGateOverride: string | null;
    compositeDivergence: number;
    tierMatch: boolean;
    decisionMatch: boolean;
    gateOverrideMatch: boolean;
    eventCount: number;
    syntheticHints: string;
}>;
export declare function getComparison(id: string): Promise<{
    id: string;
    cartValue: number;
    sessionId: string;
    pageType: string;
    evaluationId: string;
    createdAt: Date;
    prodIntentScore: number;
    prodFrictionScore: number;
    prodClarityScore: number;
    prodReceptivityScore: number;
    prodValueScore: number;
    prodCompositeScore: number;
    prodTier: string;
    prodDecision: string;
    prodGateOverride: string | null;
    shadowIntentScore: number;
    shadowFrictionScore: number;
    shadowClarityScore: number;
    shadowReceptivityScore: number;
    shadowValueScore: number;
    shadowCompositeScore: number;
    shadowTier: string;
    shadowDecision: string;
    shadowGateOverride: string | null;
    compositeDivergence: number;
    tierMatch: boolean;
    decisionMatch: boolean;
    gateOverrideMatch: boolean;
    eventCount: number;
    syntheticHints: string;
} | null>;
export declare function getComparisonsBySession(sessionId: string): Promise<{
    id: string;
    cartValue: number;
    sessionId: string;
    pageType: string;
    evaluationId: string;
    createdAt: Date;
    prodIntentScore: number;
    prodFrictionScore: number;
    prodClarityScore: number;
    prodReceptivityScore: number;
    prodValueScore: number;
    prodCompositeScore: number;
    prodTier: string;
    prodDecision: string;
    prodGateOverride: string | null;
    shadowIntentScore: number;
    shadowFrictionScore: number;
    shadowClarityScore: number;
    shadowReceptivityScore: number;
    shadowValueScore: number;
    shadowCompositeScore: number;
    shadowTier: string;
    shadowDecision: string;
    shadowGateOverride: string | null;
    compositeDivergence: number;
    tierMatch: boolean;
    decisionMatch: boolean;
    gateOverrideMatch: boolean;
    eventCount: number;
    syntheticHints: string;
}[]>;
export declare function listComparisons(options?: {
    limit?: number;
    offset?: number;
    sessionId?: string;
    tierMatch?: boolean;
    decisionMatch?: boolean;
    minDivergence?: number;
}): Promise<{
    id: string;
    cartValue: number;
    sessionId: string;
    pageType: string;
    evaluationId: string;
    createdAt: Date;
    prodIntentScore: number;
    prodFrictionScore: number;
    prodClarityScore: number;
    prodReceptivityScore: number;
    prodValueScore: number;
    prodCompositeScore: number;
    prodTier: string;
    prodDecision: string;
    prodGateOverride: string | null;
    shadowIntentScore: number;
    shadowFrictionScore: number;
    shadowClarityScore: number;
    shadowReceptivityScore: number;
    shadowValueScore: number;
    shadowCompositeScore: number;
    shadowTier: string;
    shadowDecision: string;
    shadowGateOverride: string | null;
    compositeDivergence: number;
    tierMatch: boolean;
    decisionMatch: boolean;
    gateOverrideMatch: boolean;
    eventCount: number;
    syntheticHints: string;
}[]>;
export declare function getStats(): Promise<{
    totalComparisons: number;
    tierAgreementRate: number;
    decisionAgreementRate: number;
    avgCompositeDivergence: number;
    tierMatches: number;
    tierMismatches: number;
    decisionMatches: number;
    decisionMismatches: number;
}>;
export declare function getTopDivergences(limit?: number): Promise<{
    id: string;
    cartValue: number;
    sessionId: string;
    pageType: string;
    evaluationId: string;
    createdAt: Date;
    prodIntentScore: number;
    prodFrictionScore: number;
    prodClarityScore: number;
    prodReceptivityScore: number;
    prodValueScore: number;
    prodCompositeScore: number;
    prodTier: string;
    prodDecision: string;
    prodGateOverride: string | null;
    shadowIntentScore: number;
    shadowFrictionScore: number;
    shadowClarityScore: number;
    shadowReceptivityScore: number;
    shadowValueScore: number;
    shadowCompositeScore: number;
    shadowTier: string;
    shadowDecision: string;
    shadowGateOverride: string | null;
    compositeDivergence: number;
    tierMatch: boolean;
    decisionMatch: boolean;
    gateOverrideMatch: boolean;
    eventCount: number;
    syntheticHints: string;
}[]>;
export declare function getDivergenceDistribution(): Promise<{
    tierMatch: boolean;
    decisionMatch: boolean;
    count: number;
    avgDivergence: number | null;
}[]>;
//# sourceMappingURL=shadow-comparison.repo.d.ts.map