export type CreateTrainingDatapointInput = {
    sessionId: string;
    evaluationId: string;
    interventionId: string;
    siteUrl: string;
    deviceType: string;
    referrerType: string;
    isLoggedIn: boolean;
    isRepeatVisitor: boolean;
    cartValue: number;
    cartItemCount: number;
    sessionAgeSec: number;
    totalInterventionsFired: number;
    totalDismissals: number;
    totalConversions: number;
    eventBatchIds: string;
    rawEventData: string;
    pageType: string;
    narrative: string;
    frictionsFound: string;
    intentScore: number;
    frictionScore: number;
    clarityScore: number;
    receptivityScore: number;
    valueScore: number;
    compositeScore: number;
    weightsUsed: string;
    tier: string;
    decision: string;
    gateOverride?: string;
    interventionType: string;
    actionCode: string;
    frictionId: string;
    mswimScoreAtFire: number;
    tierAtFire: string;
    outcome: string;
    conversionAction?: string;
    outcomeDelayMs?: number;
    qualityFlags?: string;
};
export declare function createDatapoint(data: CreateTrainingDatapointInput): Promise<{
    id: string;
    siteUrl: string;
    deviceType: string;
    referrerType: string;
    isLoggedIn: boolean;
    isRepeatVisitor: boolean;
    cartValue: number;
    cartItemCount: number;
    totalInterventionsFired: number;
    totalDismissals: number;
    totalConversions: number;
    sessionId: string;
    frictionId: string;
    pageType: string;
    eventBatchIds: string;
    narrative: string;
    frictionsFound: string;
    intentScore: number;
    frictionScore: number;
    clarityScore: number;
    receptivityScore: number;
    valueScore: number;
    compositeScore: number;
    weightsUsed: string;
    tier: string;
    decision: string;
    gateOverride: string | null;
    interventionType: string;
    evaluationId: string;
    actionCode: string;
    conversionAction: string | null;
    mswimScoreAtFire: number;
    tierAtFire: string;
    createdAt: Date;
    interventionId: string;
    sessionAgeSec: number;
    rawEventData: string;
    outcome: string;
    outcomeDelayMs: number | null;
    qualityFlags: string | null;
}>;
export declare function getDatapoint(id: string): Promise<{
    id: string;
    siteUrl: string;
    deviceType: string;
    referrerType: string;
    isLoggedIn: boolean;
    isRepeatVisitor: boolean;
    cartValue: number;
    cartItemCount: number;
    totalInterventionsFired: number;
    totalDismissals: number;
    totalConversions: number;
    sessionId: string;
    frictionId: string;
    pageType: string;
    eventBatchIds: string;
    narrative: string;
    frictionsFound: string;
    intentScore: number;
    frictionScore: number;
    clarityScore: number;
    receptivityScore: number;
    valueScore: number;
    compositeScore: number;
    weightsUsed: string;
    tier: string;
    decision: string;
    gateOverride: string | null;
    interventionType: string;
    evaluationId: string;
    actionCode: string;
    conversionAction: string | null;
    mswimScoreAtFire: number;
    tierAtFire: string;
    createdAt: Date;
    interventionId: string;
    sessionAgeSec: number;
    rawEventData: string;
    outcome: string;
    outcomeDelayMs: number | null;
    qualityFlags: string | null;
} | null>;
export declare function getDatapointByInterventionId(interventionId: string): Promise<{
    id: string;
    siteUrl: string;
    deviceType: string;
    referrerType: string;
    isLoggedIn: boolean;
    isRepeatVisitor: boolean;
    cartValue: number;
    cartItemCount: number;
    totalInterventionsFired: number;
    totalDismissals: number;
    totalConversions: number;
    sessionId: string;
    frictionId: string;
    pageType: string;
    eventBatchIds: string;
    narrative: string;
    frictionsFound: string;
    intentScore: number;
    frictionScore: number;
    clarityScore: number;
    receptivityScore: number;
    valueScore: number;
    compositeScore: number;
    weightsUsed: string;
    tier: string;
    decision: string;
    gateOverride: string | null;
    interventionType: string;
    evaluationId: string;
    actionCode: string;
    conversionAction: string | null;
    mswimScoreAtFire: number;
    tierAtFire: string;
    createdAt: Date;
    interventionId: string;
    sessionAgeSec: number;
    rawEventData: string;
    outcome: string;
    outcomeDelayMs: number | null;
    qualityFlags: string | null;
} | null>;
export declare function listDatapoints(options?: {
    limit?: number;
    offset?: number;
    outcome?: string;
    tier?: string;
    siteUrl?: string;
    frictionId?: string;
    interventionType?: string;
    since?: Date;
    until?: Date;
}): Promise<{
    id: string;
    siteUrl: string;
    deviceType: string;
    referrerType: string;
    isLoggedIn: boolean;
    isRepeatVisitor: boolean;
    cartValue: number;
    cartItemCount: number;
    totalInterventionsFired: number;
    totalDismissals: number;
    totalConversions: number;
    sessionId: string;
    frictionId: string;
    pageType: string;
    eventBatchIds: string;
    narrative: string;
    frictionsFound: string;
    intentScore: number;
    frictionScore: number;
    clarityScore: number;
    receptivityScore: number;
    valueScore: number;
    compositeScore: number;
    weightsUsed: string;
    tier: string;
    decision: string;
    gateOverride: string | null;
    interventionType: string;
    evaluationId: string;
    actionCode: string;
    conversionAction: string | null;
    mswimScoreAtFire: number;
    tierAtFire: string;
    createdAt: Date;
    interventionId: string;
    sessionAgeSec: number;
    rawEventData: string;
    outcome: string;
    outcomeDelayMs: number | null;
    qualityFlags: string | null;
}[]>;
export declare function countDatapoints(options?: {
    outcome?: string;
    tier?: string;
    siteUrl?: string;
}): Promise<number>;
/**
 * Get outcome distribution for diagnostics.
 */
export declare function getOutcomeDistribution(siteUrl?: string): Promise<{
    outcome: string;
    count: number;
}[]>;
/**
 * Update user feedback on a training datapoint (enrichment from InterventionFeedback).
 */
export declare function updateUserFeedback(interventionId: string, feedback: string): Promise<{
    id: string;
    siteUrl: string;
    deviceType: string;
    referrerType: string;
    isLoggedIn: boolean;
    isRepeatVisitor: boolean;
    cartValue: number;
    cartItemCount: number;
    totalInterventionsFired: number;
    totalDismissals: number;
    totalConversions: number;
    sessionId: string;
    frictionId: string;
    pageType: string;
    eventBatchIds: string;
    narrative: string;
    frictionsFound: string;
    intentScore: number;
    frictionScore: number;
    clarityScore: number;
    receptivityScore: number;
    valueScore: number;
    compositeScore: number;
    weightsUsed: string;
    tier: string;
    decision: string;
    gateOverride: string | null;
    interventionType: string;
    evaluationId: string;
    actionCode: string;
    conversionAction: string | null;
    mswimScoreAtFire: number;
    tierAtFire: string;
    createdAt: Date;
    interventionId: string;
    sessionAgeSec: number;
    rawEventData: string;
    outcome: string;
    outcomeDelayMs: number | null;
    qualityFlags: string | null;
}>;
/**
 * Get tier × outcome cross-tabulation for model analysis.
 */
export declare function getTierOutcomeCrossTab(siteUrl?: string): Promise<{
    tier: string;
    outcome: string;
    count: number;
    avgCompositeScore: number | null;
}[]>;
//# sourceMappingURL=training-datapoint.repo.d.ts.map